project 'FireBooks.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FireBooks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FireBooks
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

# Pods for Facebook
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

end
